### ISSUE TITLE
Analog output domain in setIO service

### ISSUE THREAD

**Issue by fmauch** [ros-industrial/ur_msgs#11]
Currently, the `setIO` service does not support specifying the domain (voltage / current) when setting an analog output. This should be included. Before creating a PR, I'd like to clarify whether it might be worth it, splitting the `setIO` service into multiple services, as there are quite different things this service does handle. We have the [`Analog.msg`](https://github.com/ros-industrial/ur_msgs/blob/melodic-devel/msg/Analog.msg) and [`Digital.msg`](https://github.com/ros-industrial/ur_msgs/blob/melodic-devel/msg/Digital.msg) messages already that contain the necessary fields. With defining individual services we could reuse them directly instead of adding yet another (optional) field to the `setIO` service.

In the current [`ur_robot_driver` implementation](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/src/hardware_interface.cpp#L848) we unpack the service request anyway and call different functions depending on the request's content.

**Comment by mohamedamrali1993** [comment]
Hi, Is there any update on this issue? I need to control the AO pins' voltage between 0 and 24 volts. I know the setIO is a big srv file but if we add a field for AO voltage vs. current, it would be better than not having it at all. As of now, I am not sure if the Analog and Digital msgs are useful, what topic do they work with? I am guessing you want to couple those messages in addition to the setIO service? Thanks for all of your contributions to the ROS driver!

**Comment by fmauch** [comment]
There has been no update on this matter, so far.

**Comment by zp2546265641** [comment]
> There has been no update on this matter, so far.

Hello, thank you for your help yesterday, but now I also encounter this problem, how can I set the voltage of AO, every time I send a request, it becomes current instead of voltage, at the same time the current is changed by the proportion, but the voltage is still 0V (0-10V). Unfortunately, my proportional valve shows "error" under the current signal, and it only supports voltage input 0-10v.

**Comment by fmauch** [comment]
I was just about to refer this issue in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/709

**Comment by zp2546265641** [comment]
> Hi, Is there any update on this issue? I need to control the AO pins' voltage between 0 and 24 volts. I know the setIO is a big srv file but if we add a field for AO voltage vs. current, it would be better than not having it at all. As of now, I am not sure if the Analog and Digital msgs are useful, what topic do they work with? I am guessing you want to couple those messages in addition to the setIO service? Thanks for all of your contributions to the ROS driver!
Hello, now I also encounter this problem, how can I set the voltage of AO, every time I send a request, it becomes current instead of voltage, at the same time the current is changed by the proportion, but the voltage is still 0V (0-10V). Unfortunately, my proportional valve shows "error" under the current signal, and it only supports voltage input 0-10v.

and then, how do you solve such problem?

**Comment by zp2546265641** [comment]
> Hi, Is there any update on this issue? I need to control the AO pins' voltage between 0 and 24 volts. I know the setIO is a big srv file but if we add a field for AO voltage vs. current, it would be better than not having it at all. As of now, I am not sure if the Analog and Digital msgs are useful, what topic do they work with? I am guessing you want to couple those messages in addition to the setIO service? Thanks for all of your contributions to the ROS driver!

Hello, now I also encounter this problem, how can I set the voltage of AO, every time I send a request, it becomes current instead of voltage, at the same time the current is changed by the proportion, but the voltage is still 0V (0-10V). Unfortunately, my proportional valve shows "error" under the current signal, and it only supports voltage input 0-10v.

and then, how do you solve such problem?

**Comment by zp2546265641** [comment]
> I was just about to refer this issue in [UniversalRobots/Universal_Robots_ROS_Driver#709](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/709)

hi, I just happened to search for this question and came here, and does such issue have some solve solutions?

**Comment by zp2546265641** [comment]
> I was just about to refer this issue in [UniversalRobots/Universal_Robots_ROS_Driver#709](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/709)

i use '/ur_hardware_interface/script_command' is ok, but this will cause the problem of external control interruption.

**Comment by fmauch** [comment]
I'll try to implement something...

**Comment by zp2546265641** [comment]
> I'll try to implement something...

thank you very much! great work you do! i hope for your good messgae!

**Comment by fmauch** [comment]
We should also do that for ROS 2

**Comment by fmauch** [comment]
Implemented and merged in #30
